config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'musics#index'
  resources :musics do
    resources :tracks, only: [:new, :create, :edit, :update, :destroy]
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    resources :orders, only: [:index, :create]
    collection do
      get 'search'
      end
    end
  resources :users do
  member do
    get :favorites, :following, :followers, :parchased
  end
end

resources :relationships, only: [:create, :destroy]

end

app/models/music.rb
class Music < ApplicationRecord
  belongs_to :user
  has_many :tracks, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites
  has_one :order
  has_one_attached :image

  with_options presence: true do
    validates :title, length: { maximum: 22 } 
    validates :image
    validates :artist_name, length: { maximum: 22 } 
    validates :price, format: { with: /\A[0-9]+\z/ },
                      numericality: { only_integer: true, greater_than_or_equal_to: 500, less_than_or_equal_to: 50_000 }
  end

  validates :cd_type_id, numericality: { other_than: 1 }

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :cd_type

  validate :image_content_type, if: :was_attached?

  def image_content_type
    extension = ['image/png', 'image/jpg', 'image/jpeg']
    errors.add(:image, 'の拡張子が間違っています') unless image.content_type.in?(extension)
  end

  def was_attached?
    image.attached?
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  before_action :set_music, only: [:edit, :show]
  before_action :move_to_index, except: [:index, :show, :search]

  def index
    @musics = Music.includes(:user).order('created_at DESC')
    query = 'SELECT * FROM musics'
    # @musics = Music.find_by_sql(query)
  end

  def new
    @music = Music.new
  end

  def create
    # Music.create(music_params)
    @music = Music.new(music_params)
    if @music.save
      render :create
    else
      render :new
    end
  end

  def destroy
    music = Music.find(params[:id])
    music.destroy
    music.image.purge
    redirect_to action: :index
  end

  def edit
  end

  def update
    music = Music.find(params[:id])
    music.update(music_params)
  end

  def show
    @user = User.new
    @track = Track.new
    @tracks = @music.tracks.includes(:user)
    @comment = Comment.new
    @comments = @music.comments.includes(:user)
  end

  def search
    @musics = SearchMusicsService.search(params[:keyword])
  end


  private

  def music_params
    params.require(:music).permit(:image, :title, :artist_name, :price, :cd_type_id).merge(user_id: current_user.id)
  end


  def set_music
    @music = Music.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/helpers/musics_helper.rb
module MusicsHelper
  def music_lists(musics)
    html = ''
    musics.each do |music|
      html += render(partial: 'music', locals: { music: music })
    end
    raw(html)
  end
end

app/views/musics/_music.html.erb
<div class="content_post" style="background-image: url(<%= music.image %>);" >
 <%= link_to image_tag(music.image.variant(resize:'240x240')),music_path(music.id), class: 'music-image' if music.image.attached? %>
 <% link_to 'リンク', music_path(music.id), method: :get %>
  <div class="info">
  <div class="info_show2">
    <%= music.cd_type.name %>
  </div>
    <div class="info_show1">
    <% if music.title.encode("EUC-JP").bytesize > 24 %>
      <%= music.title.slice(0, 11)... %>
    <% else %>
      <%= music.title %>
    <% end %>
    </div>
    <div class="info_show1">
    <% if music.artist_name.encode("EUC-JP").bytesize > 24 %> 
      <%= music.artist_name.slice(0, 11)... %>
    <% else %>
      <%= music.artist_name %>
    <% end %></div>
    <div class="info_show3">Upload by&nbsp;<a href="/users/<%= music.user.id %>"><%= music.user.nickname %></a></div>
    
    <div class="info_show4">
    <% if user_signed_in? && current_user.id != music.user_id %>
            <% if user_signed_in? && music.order.nil? == false %> 
              <%= "Parchased" %>
            <% else %>
              <%= link_to "¥#{music.price}", music_orders_path(music.id) %>
            <% end %>
    <% else %>
    <%= "¥#{music.price}" %>
    <% end %>
      </div>

    <% if user_signed_in? && current_user.id != music.user_id %>
        <% if music.favorited_by?(current_user) %> <!-- ログインしているユーザーがファボしたかどうかで分岐 -->
            <p class="favorite_icon"><%=link_to image_tag('favostar_after.png', size: "30x30"), music_favorites_path(music.id), method: :delete %></p>
        <% else %>
            <p class="favorite_icon"><%=link_to image_tag('favostar_before.png', size: "30x30"), music_favorites_path(music.id), method: :post %></p>
            <!--music.favorites.count ←お気に入り数の表示 使うときのため-->
        <% end %>
    <% end %>
  </div>
</div>

app/views/musics/_music_form.html.erb
      <%# form.text_field :image, placeholder: "Image Url" %>
　　　<div class="row2">Jacket Image</div>
      <%= form.file_field :image, id:"music_image", accept:"image/*" %>
       <div class="row2">Artist Name</div>
      <%= form.text_field :artist_name, placeholder: "Artist Name", rows: "10" %>
      <div class="row2">CD Title</div>
      <%= form.text_field :title, placeholder: "CD Title", rows: "10" %>
      <div class="row2">CD Type</div>
       <%= form.collection_select(:cd_type_id, CdType.all, :id, :name, {}, {class:"cd_type-select"}) %>
      <div class="row2">Selling Price</div>
      <%= form.text_field :price, placeholder: "Selling Price", rows: "10" %>
      <br><%= form.submit "SEND" %>

app/views/musics/create.html.erb
<div class="contents row row4">
  <div class="success">
    <h3>created musics</h3>
    <%=link_to "To Musics List", root_path, class:"btn"%>
  </div>
</div>

app/views/musics/destroy.html.erb
<div class="contents row row2">
  <div class="success">
    <h3>削除が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/musics/edit.html.erb
<div class="contents row row4">
  <div class="container">
    <%= form_with(model: @music, local: true) do |form| %>
      <h3>Edit musics</h3>
       <%= render partial: "music_form", locals: { form: form } %>
    <% end %>
  </div>
</div>

app/views/musics/index.html.erb
<%= form_with(url: search_musics_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "Please search for Artist Name, Song Name, Album Name~♪", class: "search-input" %>
  <%= form.submit "🔍", class: "search-btn" %>
<% end %>
<div class="contents row">
  <%= music_lists(@musics) %>
</div>

app/views/musics/new.html.erb
<div class="contents row row4">
  <div class="container">
    <%= form_with(model: @music, local: true) do |form| %>
      <h3>Upload Musics</h3>
      <%= render 'layouts/error_messages', model: form.object %>
       <%= render partial: "music_form", locals: { form: form } %>
    <% end %>
  </div>
</div>

app/views/musics/search.html.erb
<%= form_with(url: search_musics_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "Please search for Artist, Music, Album~♪", class: "search-input" %>
  <%= form.submit "🔍", class: "search-btn" %>
<% end %>
<div class="contents row">
  <% @musics.each do |music| %>
    <%= render partial: "musics/music", locals: { music: music } %>
  <% end %>
</div>

app/views/musics/show.html.erb
<div class="contents row row3">
  <div class="content_post" style="background-image: url(<%= @music.image %>);">
    <div class="more">
    <%= link_to image_tag(@music.image.variant(resize:'240x240')),rails_blob_path(@music.image), class: 'music_image' if @music.image.attached? %>
      <% if user_signed_in? && current_user.id == @music.user_id %>
        <ul class="more_list">
          <li>
            <%= link_to 'EDIT', edit_music_path(@music.id), method: :get %>
          </li>
          <li>
            <%= link_to 'DELETE', music_path(@music.id), method: :delete %>
          </li>
        </ul>
    <% end %>
    </div>
    <div class="info">
    <div class="info_show2"><%= @music.cd_type.name %></div>
    <div class="info_show1"><%= @music.title %></div>
    <div class="info_show1"><%= @music.artist_name %></div>
    <div class="info_show3">Upload by&nbsp;<a href="/users/<%= @music.user.id %>"><%= @music.user.nickname %></a></div>

    <div class="info_show4">
    <% if user_signed_in? && current_user.id != @music.user_id %>
         <% if user_signed_in? && @music.order.nil? == false %> 
              <%= "Purchased" %>
            <% else %>
    <%= link_to "¥#{@music.price}", music_orders_path(@music.id) %>
         <% end %>
    <% else %>
    <%= "¥#{@music.price}" %>
    <% end %>
      </div>
    </div>
  </div>

   <% if @music.tracks.blank? && user_signed_in? && current_user.id == @music.user_id %>
    <div class="info_show5"><%= link_to 'Upload Tracks', new_music_track_path(@music.id), method: :get %></div>
    <% end %>

    <% @music.tracks.each do |track| %>
    <%= render partial: "player", locals: { track: track } %>
<% end %>

    <% if user_signed_in? && current_user.id == @music.user_id %>
  <% @music.tracks.each do |track| %>
  <ul class="track_action">
     <li class="info_show5"><%= link_to 'Edit Tracks', edit_music_track_path(@music.id, track.id), method: :get %></li>
     <li class="info_show5"><%= link_to 'Delete Tracks', music_track_path(@music.id, track.id), method: :delete %></li>
     </ul>
       <% end %>
   <% end %>

  <div class="container2">
    <% if current_user %>
      <%= form_with(model: [@music, @comment], local: true) do |form| %>
        <%= form.text_area :text, placeholder: "Let's comment", rows: "2" %>
        <%= form.submit "SEND" %>
      <% end %>
    <% else %>
      <strong><p>Please sign up / Sign in</p></strong>
    <% end %>
       <div class="comments">
      <h4>☆Comment List☆</h4>
      <% if @comments %>
        <% @comments.each do |comment| %>
          <div class="comment_word1">
            <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>
            <td>  <%= l comment.created_at, format: :short %></td>
            <% if user_signed_in? && current_user.id == comment.user_id %>
            <%= link_to 'DELETE', music_comment_path(comment.id), method: :delete, class: "comment_delete" %>
            <% end %></strong>
          </div>
          <div class="comment_word2">
          <%= comment.text %>
          </div>  
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/musics/update.html.erb
<div class="contents row row2">
  <div class="success">
    <h3>更新が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>