config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'musics#index'
  resources :musics do
    resources :tracks, only: [:new, :create, :edit, :update, :destroy]
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    resources :orders, only: [:index, :create]
    collection do
      get 'search'
      end
    end
  resources :users do
  member do
    get :favorites, :following, :followers, :parchased
  end
end

resources :relationships, only: [:create, :destroy]

end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
 <ul>
   <% model.errors.full_messages.each do |message| %>
   <li class='error-message'><%= message %></li>
   <% end %>
 </ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MUSiA</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script type="text/javascript" src="https://js.pay.jp/v1/"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%# javascript_include_tag '/Users/itoukeisuke/TECH_CAMP/projects/musia/app/javascript/packs/application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>

  </head>
  <body>
    <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/" class="musia">MUSiA~new Whereabouts of   music~♪</a></h1>
        <% if user_signed_in? %>
          <div class="user_nav grid-6"><span><%= current_user.nickname %>
            <ul class="user__info">
              <li>
                <%= link_to "My Musics", "/users/#{current_user.id}" %>
                <%= link_to "followings", "/users/#{current_user.id}/following" %>
                <%= link_to "followers", "/users/#{current_user.id}/followers" %>
                <%= link_to "Favorites", "/users/#{current_user.id}/favorites" %>
                <%= link_to "parchased", "/users/#{current_user.id}/parchased" %>
                <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </span>
            <%= link_to "Upload", new_music_path, class: "post" %>
          </div>
        <% else %>
          <div class="grid-6">
            <%= link_to "Log In", new_user_session_path, class: "post" %>
            <%= link_to "Sign Up", new_user_registration_path, class: "post" %>
          </div>
        <% end %>
      </div>
    </header>
    <%= yield %>
    <footer>
      <p>
        Copyright MUSiA 2021.
      </p>
    </footer>
  </body>
</html>